# name: Testing
# on:
#   push:
#   pull_request:

# jobs:
#   test_project:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Run Tests
#         run: python3 -m unittest discover -p "*_test.py"
name: Testing
on:
  push:
  pull_request:

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Student Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout Hidden Tests
        uses: actions/checkout@v3
        with:
          repository: MsNamasivayam/HelloClassroomWorld-Tests
          token: ${{ secrets.TESTS_REPO_TOKEN }}
          path: hidden_tests

      - name: Move tests into place
        run: cp hidden_tests/tests/hello_test.py .

      - name: Run Tests
        run: python3 -m unittest tests